<a href="https://colab.research.google.com/github/UKD1211/100_days_ML_cX_ISI_DS/blob/main/MLR_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


In [4]:
a = np.array([1,2])

In [5]:
np.dot([1,2],[2,3])

np.int64(8)

In [6]:
np.dot(a.T,[2,3])

np.int64(8)

In [7]:
a.T.shape

(2,)

In [8]:
a = np.array([1,2,3,4]).reshape(2,2)

In [9]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [10]:
import pandas as pd
df = pd.read_csv("/content/sample_data/california_housing_train.csv")

In [11]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

In [12]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [14]:
X = df.drop(columns = ['median_house_value'])
y = df['median_house_value']

In [15]:
X

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  
0          1015.0       472.0         1.4936  
1          1129.0       463.0         1.8200  
2           333.0       117.0         1.6509  
3           515.0       226.0         3.1917  
4           624.0       262.0         1.9250  
...           ...         ...            ...  
16995       907.0       369.0         2.3571  
16996      1194.0       465.0         2.5179  
16997      1244.0       456.0         3.0313  
16998      1298.0       478.0         1.9797  
16999       806.0       270.0         3.0147  

[17000 rows x 8 columns]

In [16]:
y

0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...   
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 17000, dtype: float64

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [20]:
X_train.values

array([[-1.1807e+02,  3.3810e+01,  2.2000e+01, ...,  1.3050e+03,
         3.6800e+02,  8.5407e+00],
       [-1.1763e+02,  3.3500e+01,  1.2000e+01, ...,  1.5060e+03,
         4.9200e+02,  7.2013e+00],
       [-1.1709e+02,  3.2570e+01,  1.7000e+01, ...,  3.5700e+02,
         8.7000e+01,  5.1478e+00],
       ...,
       [-1.1815e+02,  3.3910e+01,  3.8000e+01, ...,  7.6000e+02,
         2.0800e+02,  2.9643e+00],
       [-1.1707e+02,  3.2560e+01,  9.0000e+00, ...,  3.2930e+03,
         8.4000e+02,  3.0992e+00],
       [-1.2241e+02,  3.7750e+01,  5.2000e+01, ...,  1.9320e+03,
         5.4900e+02,  2.3903e+00]])

In [37]:
class ukdMLR:
  def __init__(self):
    self.coef_ = None
    self.intercept_ = None
  def fit(self,X_train,y_train):
    X_train = np.insert(X_train,0,1,axis = 1)
    betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
    self.intercept_ = betas[0]
    self.coef_ = betas[1:]
    print(betas)
  def predict(self,X_test):
    return X_test.dot(self.coef_) + self.intercept_

In [38]:
np.insert(X_train.values,0,1,axis = 1)

array([[ 1.0000e+00, -1.1807e+02,  3.3810e+01, ...,  1.3050e+03,
         3.6800e+02,  8.5407e+00],
       [ 1.0000e+00, -1.1763e+02,  3.3500e+01, ...,  1.5060e+03,
         4.9200e+02,  7.2013e+00],
       [ 1.0000e+00, -1.1709e+02,  3.2570e+01, ...,  3.5700e+02,
         8.7000e+01,  5.1478e+00],
       ...,
       [ 1.0000e+00, -1.1815e+02,  3.3910e+01, ...,  7.6000e+02,
         2.0800e+02,  2.9643e+00],
       [ 1.0000e+00, -1.1707e+02,  3.2560e+01, ...,  3.2930e+03,
         8.4000e+02,  3.0992e+00],
       [ 1.0000e+00, -1.2241e+02,  3.7750e+01, ...,  1.9320e+03,
         5.4900e+02,  2.3903e+00]])

In [39]:
lr = ukdMLR()
lr.fit(X_train.values,y_train.values)

[-3.65225313e+06 -4.34652477e+04 -4.31063044e+04  1.13172438e+03
 -8.84326062e+00  1.13707973e+02 -3.56570769e+01  4.51475550e+01
  4.01947263e+04]


In [40]:
lr.coef_

array([-4.34652477e+04, -4.31063044e+04,  1.13172438e+03, -8.84326062e+00,
        1.13707973e+02, -3.56570769e+01,  4.51475550e+01,  4.01947263e+04])

In [41]:
lr.intercept_

np.float64(-3652253.134967171)

In [45]:
y_pred = lr.predict(X_test).values

In [46]:
y_pred

array([143770.39502896, 398615.57056332,  86341.10306674, ...,
        26482.39645055, 283556.48183115, 115808.80622305])

In [48]:
y_test.values

array([142700., 500001.,  61800., ..., 162500., 360700., 137500.])

In [49]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.6636396350241743