<a href="https://colab.research.google.com/github/UKD1211/100_days_ML_cX_ISI_DS/blob/main/ordinal_encoding_day_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("/content/customer.csv")

In [3]:
df.sample(5)

age  gender review education purchased
33   89  Female   Good        PG       Yes
48   39  Female   Good        UG       Yes
35   74    Male   Poor    School       Yes
7    60  Female   Poor    School       Yes
23   96  Female   Good    School        No

In [4]:
df = df.iloc[:,2:]

In [7]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop("purchased",axis=1),df['purchased'],test_size = 0.2
,random_state=0)

In [14]:
X_train.shape

(40, 2)

In [16]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [17]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [18]:
X_train

array([[2., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [19]:
#label encoding is only for the output columns explicitely , not the input x

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [25]:
from sklearn.model_selection import train_test_split

# Re-run train_test_split to get fresh categorical y_train and y_test
# This ensures y_train_cat and y_test_cat are in their original string format ('No', 'Yes')
_, _, y_train_cat, y_test_cat = train_test_split(df.drop("purchased",axis=1), df['purchased'], test_size = 0.2, random_state=0)

# Now, transform these categorical series using the fitted LabelEncoder
y_train = le.transform(y_train_cat)
y_test = le.transform(y_test_cat)

In [26]:
y_train

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [27]:
y_test

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 0])