<a href="https://colab.research.google.com/github/UKD1211/100_days_ML_cX_ISI_DS/blob/main/ridge_regression_nd_scratch_day_55.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [200]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge,LinearRegression
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error,r2_score

In [201]:
X,y = load_diabetes(return_X_y= True)

In [202]:
X.shape

(442, 10)

In [203]:
y.shape

(442,)

In [204]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [205]:
X_train.shape

(353, 10)

In [206]:
lr = LinearRegression()

In [207]:
lr.fit(X_train,y_train)

LinearRegression()

In [208]:
y_pred = lr.predict(X_test)

In [209]:
r2_score(y_test,y_pred)

0.4526027629719195

In [210]:
a = np.random.randint(1,100,size = 10)

In [211]:
a

array([97, 44, 40, 95, 94, 87, 23, 24, 15, 10])

In [212]:
X_train[a]

array([[-0.01277963, -0.04464164, -0.06548562, -0.06994845,  0.00118295,
         0.01684873, -0.00290283, -0.0070204 , -0.03074792, -0.05078298],
       [ 0.03081083,  0.05068012,  0.03259528,  0.04941519, -0.04009564,
        -0.04358892, -0.06917231,  0.03430886,  0.06301517,  0.00306441],
       [-0.10722563, -0.04464164, -0.07734155, -0.02632753, -0.08962994,
        -0.09619786,  0.02655027, -0.0763945 , -0.04257085, -0.0052198 ],
       [ 0.05260606, -0.04464164, -0.00405033, -0.03090652, -0.0469754 ,
        -0.0583069 , -0.01394774, -0.02583997,  0.03606033,  0.02377494],
       [-0.04547248,  0.05068012, -0.04716281, -0.01599898, -0.04009564,
        -0.02480001,  0.00077881, -0.03949338, -0.06291688, -0.03835666],
       [-0.02730979, -0.04464164,  0.08001901,  0.09875125, -0.00294491,
         0.01810133, -0.01762938,  0.00331192, -0.02952643,  0.03620126],
       [ 0.06350368, -0.04464164, -0.05039625,  0.10794366,  0.03145391,
         0.01935392, -0.01762938,  0.02360753

In [213]:
y_train[a]

array([ 96., 208., 137., 198., 138., 257., 189., 173., 197.,  72.])

In [214]:
y_new_pred = lr.predict(X_train[a])

In [215]:
y_new_pred

array([ 81.93161087, 234.56256175,  92.34075672, 183.05957367,
        71.78241048, 229.02916335, 203.78762568, 212.10045329,
       150.77793462,  64.07814485])

In [216]:
mean_squared_error(y_train[a],y_new_pred)

1223.504491103329

In [217]:
r2_score(y_train[a],y_new_pred)

0.5625106856048026

In [218]:
lr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [219]:
lr.intercept_

np.float64(151.34560453985995)

In [220]:
#possibly the overfitting maybe happens

In [221]:
rr = Ridge(alpha = 0.25)

In [222]:
rr.fit(X_train,y_train)

Ridge(alpha=0.25)

In [223]:
y_pred_rr = rr.predict(X_test)

In [224]:
r2_score(y_test,y_pred_rr)

0.46013854270226506

In [225]:
rr.coef_

array([  44.27239915, -166.63285876,  445.80343528,  286.32913635,
        -57.65208569,  -83.23120238, -189.39534933,  140.60491128,
        339.62265865,   99.99565285])

In [226]:
rr.intercept_

np.float64(151.65043505878887)

In [227]:
#now we will be creating our own class

In [247]:
class UKDrr_nd:
  def __init__(self,alpha=0.1):
    self.coef_ = None
    self.intercept_ = None
    self.alpha = alpha

  def fit(self,X_train,y_train):

    X_train_new = np.insert(X_train,0,1,axis=1)
    betas = np.linalg.inv(np.dot(X_train_new.T,X_train_new) + self.alpha * np.identity(X_train_new.shape[1])).dot(X_train_new.T).dot(y_train)
    self.coef_ = betas[1:]
    self.intercept_ = betas[0]

    print(self.coef_)
    print(self.intercept_)

  def predict(self,X_test):
    return np.dot(X_test,self.coef_) + self.intercept_

In [248]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [249]:
X_train.shape

(353, 10)

In [250]:
X_train_new = np.insert(X_train,0,1,axis=1)

In [251]:
X_train_new.shape

(353, 11)

In [252]:
betas = np.linalg.inv(np.dot(X_train_new.T,X_train_new) + 0.1 * np.identity(X_train_new.shape[1])).dot(X_train_new.T).dot(y_train)

In [253]:
betas

array([ 151.41552984,   42.87709893, -205.49834268,  505.10960427,
        317.09526097, -108.51126124,  -86.2562279 , -190.37246178,
        151.70037599,  392.29679967,   79.93194581])

In [254]:
rr = UKDrr_nd(alpha = 0.24)

In [255]:
rr.fit(X_train,y_train)

[  44.23387563 -168.84903392  449.28915932  288.15555227  -59.61581654
  -84.1811245  -189.99517712  141.06216084  342.29330441   99.13863554]
151.53541817940035


In [256]:
rr.predict(X_test)

array([147.46598032, 173.35594974, 146.26686584, 277.47725035,
       130.45310768, 106.62783057, 242.47210565, 190.79650382,
        95.2762816 , 120.71794399, 102.6397269 , 152.80988419,
        71.72869641, 204.56432085, 110.17156102, 135.29962821,
       217.44307064, 238.43014428, 185.64842139, 208.24754825,
       193.80118482,  97.59641624,  82.97424889, 185.9486214 ,
       151.88151575, 163.45363822, 184.08412143, 174.16596562,
        60.22441472, 122.86199751, 176.826008  ,  99.66611326,
       136.31619485, 179.90160192, 172.84539624, 187.22953744,
       130.38857314, 128.97181419, 155.29261792,  70.41240994,
        88.24810735, 116.67107215, 157.71985496, 156.46408702,
       171.66150813,  74.9492704 ,  87.63744886, 108.15433521,
        69.53157633, 153.51954828, 148.89701403,  73.54958277,
       122.64974972, 113.31167412, 172.24162912, 152.21593732,
       104.97656207, 197.19719876, 118.10469414,  75.00295584,
       182.42153898, 189.64716696, 140.64465308, 116.52