<a href="https://colab.research.google.com/github/UKD1211/100_days_ML_cX_ISI_DS/blob/main/ridge_regression_gradient_descent_day_55.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [101]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDRegressor,LinearRegression
from sklearn.metrics import r2_score
from sklearn.datasets import load_diabetes

In [102]:
X,y = load_diabetes(return_X_y=True)

In [103]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.2,random_state = 42)

In [104]:
lr = LinearRegression()

In [105]:
lr.fit(X_train,y_train)

LinearRegression()

In [106]:
r2_score(y_test,lr.predict(X_test))

0.4526027629719195

In [107]:
sgd = SGDRegressor(max_iter=1000,learning_rate='constant',eta0=0.01)

In [108]:
sgd.fit(X_train,y_train)

SGDRegressor(learning_rate='constant')

In [109]:
r2_score(y_test,sgd.predict(X_test))

0.4527193735776994

In [110]:
sgd.coef_

array([  54.55576554, -113.86538478,  394.0941125 ,  267.48950264,
        -15.02554638,  -55.79900034, -191.46859632,  147.87537928,
        304.66027343,  145.91034086])

In [111]:
sgd.intercept_

array([151.32899147])

In [112]:
#now making my own class here

In [113]:
import numpy as np

class UKDrgd:
    def __init__(self, learning_rate=0.01, epochs=1000, alpha=0.01):
        self.lr = learning_rate
        self.epochs = epochs
        self.alpha = alpha
        self.coef_ = None

    def fit(self, X_train, y_train):
        n_samples, n_features = X_train.shape

        # initialize weights
        self.coef_ = np.zeros(n_features)

        for _ in range(self.epochs):
            # prediction
            y_pred = np.dot(X_train, self.coef_)

            # gradient (Ridge)
            gradient = (1/n_samples) * np.dot(X_train.T, (y_pred - y_train)) \
                       + self.alpha * self.coef_

            # update
            self.coef_ = self.coef_ - self.lr * gradient

        print("Weights:", self.coef_)

    def predict(self, X_test):
        return np.dot(X_test, self.coef_)


In [114]:
a = np.ones(X_train.shape[1]+1)

In [115]:
a[0] = 0

In [116]:
a

array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [117]:
rgd = UKDrgd(learning_rate=0.1,epochs = 200,alpha = 0.01)

In [118]:
rgd.fit(X_train,y_train)

Weights: [ 15.52143739   0.13272355  42.68935466  31.63746626  10.0538471
   6.41030523 -26.28955251  27.02559688  37.92912915  29.51777778]
